require('dotenv').config();
const express=require('express'),cors=require('cors'),mongoose=require('mongoose'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),multer=require('multer'),path=require('path'),fs=require('fs');
const {User,Color,Product,Project,Pattern}=require('./models');
const app=express(),PORT=process.env.PORT||5000,uploadDir=path.join(__dirname,'uploads');
if(!fs.existsSync(uploadDir))fs.mkdirSync(uploadDir,{recursive:true});
app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:4200'}));app.use(express.json({limit:'5mb'}));app.use('/uploads',express.static(uploadDir));
const storage=multer.diskStorage({destination:(_,__,cb)=>cb(null,uploadDir),filename:(_,file,cb)=>cb(null,`${Date.now()}-${file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_')}`)});
const upload=multer({storage,limits:{fileSize:8*1024*1024},fileFilter:(_,file,cb)=>{const ok=/image\/(jpeg|png|jpg)/.test(file.mimetype);cb(ok?null:new Error('Only JPG/PNG images are allowed'),ok)}});
const secret=()=>process.env.JWT_SECRET||'dev-secret';
function sign(u){return jwt.sign({id:u._id,role:u.role},secret(),{expiresIn:'2h'})}
function auth(req,res,next){const h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({message:'Authentication required'});try{req.user=jwt.verify(t,secret());next()}catch{res.status(401).json({message:'Invalid or expired token'})}}
function admin(req,res,next){if(req.user.role!=='Admin')return res.status(403).json({message:'Admin access required'});next()}
app.get('/api/health',(_,res)=>res.json({ok:true,service:'Smart Wall Paint Visualizer API'}));
app.post('/api/auth/register',async(req,res)=>{try{const{name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required'});if(password.length<6)return res.status(400).json({message:'Password must be at least 6 characters'});if(await User.findOne({email:email.toLowerCase()}))return res.status(409).json({message:'Email already registered'});const u=await User.create({name,email:email.toLowerCase(),password:await bcrypt.hash(password,10)});res.status(201).json({token:sign(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const u=await User.findOne({email:(req.body.email||'').toLowerCase()});if(!u||!(await bcrypt.compare(req.body.password||'',u.password)))return res.status(401).json({message:'Invalid email or password'});res.json({token:sign(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/colors',async(_,res)=>res.json(await Color.find().sort({category:1,name:1})));app.post('/api/colors',auth,admin,async(req,res)=>res.status(201).json(await Color.create(req.body)));app.put('/api/colors/:id',auth,admin,async(req,res)=>res.json(await Color.findByIdAndUpdate(req.params.id,req.body,{new:true})));app.delete('/api/colors/:id',auth,admin,async(req,res)=>{await Color.findByIdAndDelete(req.params.id);res.json({ok:true})});
app.get('/api/products',async(_,res)=>res.json(await Product.find().sort({createdAt:-1})));app.post('/api/products',auth,admin,async(req,res)=>res.status(201).json(await Product.create(req.body)));app.put('/api/products/:id',auth,admin,async(req,res)=>res.json(await Product.findByIdAndUpdate(req.params.id,req.body,{new:true})));app.delete('/api/products/:id',auth,admin,async(req,res)=>{await Product.findByIdAndDelete(req.params.id);res.json({ok:true})});
app.post('/api/upload',auth,upload.single('room'),(req,res)=>{if(!req.file)return res.status(400).json({message:'Image required'});res.json({url:`/uploads/${req.file.filename}`,filename:req.file.filename})});
app.get('/api/projects',auth,async(req,res)=>res.json(await Project.find(req.user.role==='Admin'?{}:{userId:req.user.id}).sort({updatedAt:-1})));app.post('/api/projects',auth,async(req,res)=>res.status(201).json(await Project.create({...req.body,userId:req.user.id})));app.put('/api/projects/:id',auth,async(req,res)=>{const p=await Project.findOne({_id:req.params.id,...(req.user.role==='Admin'?{}:{userId:req.user.id})});if(!p)return res.status(404).json({message:'Project not found'});Object.assign(p,req.body);res.json(await p.save())});
app.get('/api/patterns',async(_,res)=>res.json(await Pattern.find()));app.post('/api/patterns',auth,admin,async(req,res)=>res.status(201).json(await Pattern.create(req.body)));
app.get('/api/admin/activity',auth,admin,async(_,res)=>{const[users,projects,products,colors]=await Promise.all([User.countDocuments(),Project.countDocuments(),Product.countDocuments(),Color.countDocuments()]);res.json({users,projects,products,colors})});
async function seed(){if(await Color.countDocuments()===0)await Color.insertMany([{name:'Terracotta Glow',hex:'#C65D3B',rgb:'198,93,59',category:'Warm',finish:'Matte',coverage:120,price:1499,rating:4.8},{name:'Cobalt Calm',hex:'#2855C5',rgb:'40,85,197',category:'Cool',finish:'Silk',coverage:130,price:1699,rating:4.7},{name:'Ivory Sand',hex:'#E8DCC7',rgb:'232,220,199',category:'Neutral',finish:'Matt',coverage:125,price:1299,rating:4.6},{name:'Forest Leaf',hex:'#3E6B4B',rgb:'62,107,75',category:'Earthy',finish:'Matt',coverage:120,price:1599,rating:4.9},{name:'Sun Pop',hex:'#F4C542',rgb:'244,197,66',category:'Bold',finish:'Silk',coverage:115,price:1399,rating:4.5},{name:'Lavender Mist',hex:'#B9A4D6',rgb:'185,164,214',category:'Pastel',finish:'Matt',coverage:125,price:1499,rating:4.7}]);if(await Product.countDocuments()===0)await Product.insertMany([{name:'Terracotta Glow',shade:'TC-401',finish:'Matte',coverage:120,price:1499,rating:4.8,category:'Warm'},{name:'Cobalt Calm',shade:'CB-210',finish:'Silk',coverage:130,price:1699,rating:4.7,category:'Cool'},{name:'Ivory Sand',shade:'NS-101',finish:'Matt',coverage:125,price:1299,rating:4.6,category:'Neutral'},{name:'Forest Leaf',shade:'ER-332',finish:'Matt',coverage:120,price:1599,rating:4.9,category:'Earthy'}]);if(!await User.findOne({email:'admin@smartwall.com'}))await User.create({name:'Smart Wall Admin',email:'admin@smartwall.com',password:await bcrypt.hash('Admin@123',10),role:'Admin'})}
mongoose.connect(process.env.MONGO_URI||'').then(async()=>{console.log('MongoDB connected');await seed()}).catch(e=>console.error('MongoDB connection failed:',e.message));
app.use((err,_,res,__)=>res.status(400).json({message:err.message||'Request failed'}));app.listen(PORT,()=>console.log(`API running on http://localhost:${PORT}`));
